if (not scpm_server)
    set(scpm_server "https://raw.githubusercontent.com/pperehozhih/scpm/master")
endif()

function(scpm_install package_name, package_version, package_chroot)
    if (NOT EXISTS ${CMAKE_CURRENT_BINARY_DIR}/scpm/${package_name}${package_version}.cmake)
        file(DOWNLOAD "${scpm_server}/packages/${package_name}.cmake" "${CMAKE_CURRENT_BINARY_DIR}/scpm/${package_name}${package_version}.cmake")
        include("${CMAKE_CURRENT_BINARY_DIR}/scpm/${package_name}${package_version}.cmake")
    endif()
endfunction(scpm_install)
